apiVersion: v2
name: dash
description: A Helm chart for the m9sweeper Dashboard and API
type: application
version: 1.1.0
appVersion: 1.1.0
maintainers:
  - email: info@m9sweeper.io
    name: m9sweeper Support Team