name: Docker Build

on:
  workflow_call:
    inputs:
      dash-image-tags:
        required: true
        type: string
      trawler-image-tags:
        required: true
        type: string
      build-all-architectures:
        required: false
        type: boolean
        default: false
      push-images:
        required: false
        type: boolean
        default: true

jobs:
  docker_dash:
    name: Build Dash Image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        if: inputs.build-all-architectures && inputs.push-images == true
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["public-docker.nexus.celestialdata.net"]

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: inputs.push-images == true
        with:
          registry: ghcr.io
          username: m9sweeper
          password: ${{ github.token }}

      - name: Build & Push Dash (amd64)
        uses: docker/build-push-action@v4
        if: inputs.build-all-architectures == false && inputs.push-images == true
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ inputs.dash-image-tags }}
          cache-from: type=gha,scope=build-dash-amd64
          cache-to: type=gha,mode=max,scope=build-dash-amd64

      - name: Build & Push Dash (all architectures)
        uses: docker/build-push-action@v4
        if: inputs.build-all-architectures && inputs.push-images == true
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ inputs.dash-image-tags }}
          cache-from: type=gha,scope=build-dash-all-archs
          cache-to: type=gha,mode=max,scope=build-dash-all-archs

      - name: Build & Export Dash
        uses: docker/build-push-action@v4
        if: inputs.push-images == false
        with:
          context: .
          push: false
          provenance: false
          tags: ${{ inputs.dash-image-tags }}
          cache-from: type=gha,scope=build-dash-amd64
          cache-to: type=gha,mode=max,scope=build-dash-amd64
          outputs: type=docker,dest=/tmp/dash.tar

      - name: Upload Dash Image Archive
        uses: actions/upload-artifact@v3
        if: inputs.push-images == false
        with:
          path: /tmp/dash.tar
          name: dash
          retention-days: 5

  docker_trawler:
    name: Build Trawler Image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        if: inputs.build-all-architectures && inputs.push-images == true
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["public-docker.nexus.celestialdata.net"]

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: inputs.push-images == true
        with:
          registry: ghcr.io
          username: m9sweeper
          password: ${{ github.token }}

      - name: Build & Push Trawler (amd64)
        uses: docker/build-push-action@v4
        if: inputs.build-all-architectures == false && inputs.push-images == true
        with:
          context: trawler/
          push: true
          provenance: false
          tags: ${{ inputs.trawler-image-tags }}
          cache-from: type=gha,scope=build-trawler-amd64
          cache-to: type=gha,mode=max,scope=build-trawler-amd64

      - name: Build & Push Trawler (all architectures)
        uses: docker/build-push-action@v4
        if: inputs.build-all-architectures && inputs.push-images == true
        with:
          context: trawler/
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ inputs.trawler-image-tags }}
          cache-from: type=gha,scope=build-trawler-all-archs
          cache-to: type=gha,mode=max,scope=build-trawler-all-archs

      - name: Build & Export Trawler
        uses: docker/build-push-action@v4
        if: inputs.push-images == false
        with:
          context: trawler/
          push: false
          provenance: false
          tags: ${{ inputs.trawler-image-tags }}
          cache-from: type=gha,scope=build-trawler-amd64
          cache-to: type=gha,mode=max,scope=build-trawler-amd64
          outputs: type=docker,dest=/tmp/trawler.tar

      - name: Upload Trawler Image Archive
        uses: actions/upload-artifact@v3
        if: inputs.push-images == false
        with:
          path: /tmp/trawler.tar
          name: trawler
          retention-days: 5